config/routes.rb
Rails.application.routes.draw do

  resources :check_box_samples
  devise_for :users

  post 'upload' => 'home#upload'

  root to: 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_writer :val, :vec
  def val

  end
  def vec

  end

  @@tate = 64
  @@yoko = 64

  def tate(num)
    @@tate = num
  end

  def yoko(num)
    @@yoko = num
  end

  def self.tate
    @@tate
  end

  def self.yoko
    @@yoko
  end

  mount_uploader :image, ImageUploader
end

app/models/check_box_sample.rb
class CheckBoxSample < ActiveRecord::Base
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :target, class_name: 'User', foreign_key: 'target_id'
  belongs_to :from, class_name: 'User', foreign_key: 'from_id'
end

app/models/relation_tag.rb
class RelationTag < ActiveRecord::Base
  belongs_to :to_tag, class_name: 'Tag', foreign_key: 'tag_code'
  belongs_to :to_user, class_name: 'User', foreign_key: 'relation_code'
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # タグ紐付
  has_many :to_user_f, class_name: 'RelationTag', foreign_key: :tag_code
  has_many :to_user, through: :to_user_f, source: 'to_user'
end

app/models/user.rb
class User < ActiveRecord::Base

  # フォロー・フォロワーの紐付
  has_many :follows_f, class_name: 'Relation', foreign_key: :from_id
  has_many :followings, through: :follows_f, source: 'target'

  has_many :followers_f, class_name: 'Relation', foreign_key: :target_id
  has_many :followers, through: :followers_f, source: 'from'

  # タグ紐付
  has_many :to_tags_f, class_name: 'RelationTag', foreign_key: :relation_code
  has_many :tagging, through: :to_tags_f, source: 'to_tag'


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # ログインパラメータのアクセサ
  attr_accessor :login

  # validates :username,
  #           uniqueness: { case_sensitive: :false },
  #           length: { minimum: 4, maximum: 20 }

  # フォロー等の機能

  # フォロー
  def follow user
    followings << user
  end

  # フォロー解除
  def unfollow user
    followings.destroy user
  end

  # フォローしてるユーザかの判定
  def followed? user
    followings.include? user
  end

  # フォローされているか？
  def follower? user
    user.followers.include? user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # ログイン前の場合、ログイン画面にリダイレクト
  #before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/check_box_samples_controller.rb
class CheckBoxSamplesController < ApplicationController

  def index
    @checkbox = CheckBoxSample.find(1)
  end

  # 登録画面表示
  def new
    @checkbox = CheckBoxSample.new
  end

  # 登録処理実行
  def create
    CheckBoxSample.create(status_param)
    redirect_to root_path
  end

  # 編集画面表示
  def edit
    @checkbox = CheckBoxSample.find(1)
  end

  private
    def status_param
      params.require(:check_box_sample).permit(:status)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @book = Book.new
  end

  def upload
    @book = Book.new
    @book.tate(book_params[:val])
    @book.yoko(book_params[:vec])
    Book.create(book_params)
    render :template => 'home/index'
  end

  private

  def book_params
    params.require(:book).permit(:image, :val, :vec)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_box_samples_helper.rb
module CheckBoxSamplesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/check_box_samples/edit.html.erb
<h1>CheckBoxSample#edit</h1>
<%= form_for(@checkbox) do  |f|%>
    <label><%= f.radio_button :status, "1" %>done</label>
    <label><%= f.radio_button :status, "2" %>doing</label>
    <%= f.submit '登録' %>
<% end %>

app/views/check_box_samples/index.html.erb
<h1>CheckBoxSample#index</h1>
<%= link_to "登録画面へ", new_check_box_sample_path %>
<%= link_to "編集画面へ", edit_check_box_sample_path(@checkbox) %>
<p>Find me in app/views/home/index.html.erb</p>

app/views/check_box_samples/new.html.erb
<h1>CheckBoxSample#new</h1>
<%= form_for(@checkbox) do  |f|%>
    <label><%= f.radio_button :status, "1" %>done</label>
    <label><%= f.radio_button :status, "2" %>doing</label>
    <%= f.submit '登録' %>


<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%=  form_for @book, :url => {:action => 'upload'} do |f|%>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.text_field :val %>
    <%= f.text_field :vec %>
    <%= f.submit '投稿' %>
  </div>
<% end %>

<% if @book.image? %>
  <%= image_tag @book.image.thumb.url %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabPj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if user_signed_in? %>
    <p>{<%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
  <% end %>

<%= yield %>

</body>
</html>